---

language: node_js

node_js: lts/*

script:
  # - npm audit
  - npm run lint
  - npm run prepare
  - npm run build

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      repo: system76/web-design
      branch: master

  - provider: pages
    skip_cleanup: true
    github-token: $GH_TOKEN
    local-dir: docs
    keep-history: true
    on:
      repo: system76/web-design
      tags: true
